const Imagens = [
  { id: 1, src: './img1.jpg', type: 'jpg' },
  { id: 2, src: './img2.jpg', type: 'jpg' },
  { id: 3, src: './img3.jpg', type: 'jpg' },
  { id: 4, src: './img4.jpg', type: 'jpg' },
  { id: 5, src: './img5.jpg', type: 'jpg' },
  { id: 6, src: './img6.jpg', type: 'jpg' },
  { id: 7, src: './img7.jpg', type: 'jpg' },
  { id: 8, src: './img8.jpg', type: 'jpg' },
  { id: 9, src: './img9.jpg', type: 'jpg' },
  { id: 10, src: './img10.jpg', type: 'jpg' },
  { id: 11, src: './img11.jpg', type: 'jpg' },
  { id: 12, src: './img12.jpg', type: 'jpg' },
  { id: 13, src: './img13.jpg', type: 'jpg' },
  { id: 14, src: './img14.jpg', type: 'jpg' },
  { id: 15, src: './img15.jpg', type: 'jpg' },
  { id: 16, src: './img16.jpg', type: 'jpg' },
  { id: 17, src: './img17.jpg', type: 'jpg' },
  { id: 18, src: './img18.jpg', type: 'jpg' },
  { id: 19, src: './img19.jpg', type: 'jpg' },
  { id: 20, src: './img20.jpg', type: 'jpg' },
  { id: 21, src: './img21.jpg', type: 'jpg' },
  { id: 22, src: './img22.jpg', type: 'jpg' },
  { id: 23, src: './img23.jpg', type: 'jpg' },
  { id: 24, src: './img24.jpg', type: 'jpg' },
  { id: 25, src: './img25.jpg', type: 'jpg' },
  { id: 26, src: './img26.jpg', type: 'jpg' },
  { id: 27, src: './img27.jpg', type: 'jpg' },
  { id: 28, src: './img28.jpg', type: 'jpg' },
  { id: 29, src: './img29.jpg', type: 'jpg' },
  { id: 30, src: './img30.jpg', type: 'jpg' },
  { id: 31, src: './img31.mp4', type: 'mp4' },
  { id: 32, src: './img32.mp4', type: 'mp4' },
  { id: 33, src: './img33.mp4', type: 'mp4' },
  { id: 34, src: './img34.mp4', type: 'mp4' },
  { id: 35, src: './img35.mp4', type: 'mp4' },
  { id: 36, src: './img36.mp4', type: 'mp4' },
  { id: 37, src: './img37.jpg', type: 'jpg' },
  { id: 38, src: './img38.jpg', type: 'jpg' },
  { id: 39, src: './img39.jpg', type: 'jpg' },
  { id: 40, src: './img40.jpg', type: 'jpg' },
  { id: 41, src: './img41.jpg', type: 'jpg' },
  { id: 42, src: './img42.jpg', type: 'jpg' },
  { id: 43, src: './img43.jpg', type: 'jpg' },
];

export default Imagens;